### ISSUE TITLE
Survey Data

### ISSUE THREAD

**Issue by tell029** [iNZightVIT/iNZightVIT-WIN#3]
When users specify and survey design for their data, iNZight needs to account for weighting in all of its computations. For now, these features have been disabled until a time that we can implement them properly. This includes visual and textual summary information.

Additionally, any modifications to the data need to be applied to the survey object. Once I figure out how to add observers to these events, I can proceed with this.

**Comment by tell029** [comment]
@chriswild

**Comment by chriswild** [comment]
“Once I figure out how to add observers to these events, I can proceed with this”
-- Good luck!!

**Comment by tell029** [comment]
For now, the survey object is being created from the current state of the data set each time a plot is drawn. This is computationally inefficient for now, but until a more stable alternative can be implemented, it will have to make do.
